// <auto-generated />
using System;
using BiletSatis.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BiletSatis.Infrastructure.Migrations
{
    [DbContext(typeof(BiletSatisDbContext))]
    partial class BiletSatisDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BiletSatis.Domain.Entities.Bilet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EtkinlikBolumId")
                        .HasColumnType("int");

                    b.Property<int?>("IndirimId")
                        .HasColumnType("int");

                    b.Property<int?>("KoltukId")
                        .HasColumnType("int");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("int");

                    b.Property<decimal>("OdenenTutar")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("SatinAlmaZamani")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EtkinlikBolumId");

                    b.HasIndex("IndirimId");

                    b.HasIndex("KoltukId");

                    b.HasIndex("KullaniciId");

                    b.ToTable("Biletler");
                });

            modelBuilder.Entity("BiletSatis.Domain.Entities.Bolum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Oturmali")
                        .HasColumnType("bit");

                    b.Property<int>("SalonId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SalonId");

                    b.ToTable("Bolumler");
                });

            modelBuilder.Entity("BiletSatis.Domain.Entities.Etkinlik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Isim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SalonId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SalonId");

                    b.ToTable("Etkinlikler");
                });

            modelBuilder.Entity("BiletSatis.Domain.Entities.EtkinlikBolum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BolumId")
                        .HasColumnType("int");

                    b.Property<int>("EtkinlikId")
                        .HasColumnType("int");

                    b.Property<decimal>("Fiyat")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Kontenjan")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BolumId");

                    b.HasIndex("EtkinlikId");

                    b.ToTable("EtkinlikBolumleri");
                });

            modelBuilder.Entity("BiletSatis.Domain.Entities.Indirim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Yuzde")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.ToTable("Indirimler");
                });

            modelBuilder.Entity("BiletSatis.Domain.Entities.Koltuk", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Blok")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BolumId")
                        .HasColumnType("int");

                    b.Property<string>("KoltukNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sira")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BolumId");

                    b.ToTable("Koltuklar");
                });

            modelBuilder.Entity("BiletSatis.Domain.Entities.Kullanici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Eposta")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Rol")
                        .HasColumnType("int");

                    b.Property<string>("SifreHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Eposta")
                        .IsUnique();

                    b.ToTable("Kullanicilar");
                });

            modelBuilder.Entity("BiletSatis.Domain.Entities.Rezervasyon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EtkinlikBolumId")
                        .HasColumnType("int");

                    b.Property<int?>("KoltukId")
                        .HasColumnType("int");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturmaZamani")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SonGecerlilik")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EtkinlikBolumId");

                    b.HasIndex("KoltukId");

                    b.HasIndex("KullaniciId");

                    b.ToTable("Rezervasyonlar");
                });

            modelBuilder.Entity("BiletSatis.Domain.Entities.Salon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Adres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Salonlar");
                });

            modelBuilder.Entity("BiletSatis.Domain.Entities.Bilet", b =>
                {
                    b.HasOne("BiletSatis.Domain.Entities.EtkinlikBolum", "EtkinlikBolum")
                        .WithMany("Biletler")
                        .HasForeignKey("EtkinlikBolumId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BiletSatis.Domain.Entities.Indirim", "Indirim")
                        .WithMany("Biletler")
                        .HasForeignKey("IndirimId");

                    b.HasOne("BiletSatis.Domain.Entities.Koltuk", "Koltuk")
                        .WithMany()
                        .HasForeignKey("KoltukId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BiletSatis.Domain.Entities.Kullanici", "Kullanici")
                        .WithMany("Biletler")
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EtkinlikBolum");

                    b.Navigation("Indirim");

                    b.Navigation("Koltuk");

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("BiletSatis.Domain.Entities.Bolum", b =>
                {
                    b.HasOne("BiletSatis.Domain.Entities.Salon", "Salon")
                        .WithMany("Bolumler")
                        .HasForeignKey("SalonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Salon");
                });

            modelBuilder.Entity("BiletSatis.Domain.Entities.Etkinlik", b =>
                {
                    b.HasOne("BiletSatis.Domain.Entities.Salon", "Salon")
                        .WithMany("Etkinlikler")
                        .HasForeignKey("SalonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Salon");
                });

            modelBuilder.Entity("BiletSatis.Domain.Entities.EtkinlikBolum", b =>
                {
                    b.HasOne("BiletSatis.Domain.Entities.Bolum", "Bolum")
                        .WithMany("EtkinlikBolumleri")
                        .HasForeignKey("BolumId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BiletSatis.Domain.Entities.Etkinlik", "Etkinlik")
                        .WithMany("EtkinlikBolumleri")
                        .HasForeignKey("EtkinlikId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bolum");

                    b.Navigation("Etkinlik");
                });

            modelBuilder.Entity("BiletSatis.Domain.Entities.Koltuk", b =>
                {
                    b.HasOne("BiletSatis.Domain.Entities.Bolum", "Bolum")
                        .WithMany("Koltuklar")
                        .HasForeignKey("BolumId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bolum");
                });

            modelBuilder.Entity("BiletSatis.Domain.Entities.Rezervasyon", b =>
                {
                    b.HasOne("BiletSatis.Domain.Entities.EtkinlikBolum", "EtkinlikBolum")
                        .WithMany("Rezervasyonlar")
                        .HasForeignKey("EtkinlikBolumId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BiletSatis.Domain.Entities.Koltuk", "Koltuk")
                        .WithMany()
                        .HasForeignKey("KoltukId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BiletSatis.Domain.Entities.Kullanici", "Kullanici")
                        .WithMany("Rezervasyonlar")
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EtkinlikBolum");

                    b.Navigation("Koltuk");

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("BiletSatis.Domain.Entities.Bolum", b =>
                {
                    b.Navigation("EtkinlikBolumleri");

                    b.Navigation("Koltuklar");
                });

            modelBuilder.Entity("BiletSatis.Domain.Entities.Etkinlik", b =>
                {
                    b.Navigation("EtkinlikBolumleri");
                });

            modelBuilder.Entity("BiletSatis.Domain.Entities.EtkinlikBolum", b =>
                {
                    b.Navigation("Biletler");

                    b.Navigation("Rezervasyonlar");
                });

            modelBuilder.Entity("BiletSatis.Domain.Entities.Indirim", b =>
                {
                    b.Navigation("Biletler");
                });

            modelBuilder.Entity("BiletSatis.Domain.Entities.Kullanici", b =>
                {
                    b.Navigation("Biletler");

                    b.Navigation("Rezervasyonlar");
                });

            modelBuilder.Entity("BiletSatis.Domain.Entities.Salon", b =>
                {
                    b.Navigation("Bolumler");

                    b.Navigation("Etkinlikler");
                });
#pragma warning restore 612, 618
        }
    }
}
